# Generated by Django 5.2.17 on 2026-10-01 19:31

from django.db import migrations

STARTING_TAGS = [
    "Python",
    "JavaScript",
    "TypeScript",
    "HTML & CSS",
    "React",
    "Django",
    "Node.js",
    "SQL & Databases",
    "Git",
    "Testing",
    "APIs",
    "Docker & DevOps",
    "Cloud",
    "AI & Machine Learning",
    "Data Analysis",
    "UX Research",
    "UI Design",
    "Figma",
    "Accessibility",
    "Product Management",
    "Agile & Scrum",
]


def create_tags(apps, schema_editor):
    Tag = apps.get_model("core", "Tag")
    Tag.objects.bulk_create(Tag(name=name) for name in STARTING_TAGS)


def delete_tags(apps, schema_editor):
    apps.get_model("core", "Tag").objects.filter(name__in=STARTING_TAGS).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_tags, delete_tags),
    ]
