# Generated by Django 5.2.17 on 2026-10-01 19:31

from django.db import migrations

STARTING_COHORTS = ["Cohort 1", "Cohort 2", "Cohort 3"]


def create_cohorts(apps, schema_editor):
    Cohort = apps.get_model("accounts", "Cohort")
    Cohort.objects.bulk_create(Cohort(name=name) for name in STARTING_COHORTS)


def delete_cohorts(apps, schema_editor):
    Cohort = apps.get_model("accounts", "Cohort")
    Cohort.objects.filter(name__in=STARTING_COHORTS).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_cohort_profile"),
    ]

    operations = [
        migrations.RunPython(create_cohorts, delete_cohorts),
    ]
